---
# This playbook runs post scripts 
# necessary for final cleaning up
# before fully completing deployment

- name: Configure WSUS
  hosts: wsus
  gather_facts: true
  tasks:
    - name: Install and Configure WSUS
      script: ./ps-scripts/configure-wsus.ps1
    - name: Restart Machine
      script: ./ps-scripts/shutdown.ps1
      ignore_errors: yes
    - pause: minutes=7
    # - name: waiting for server to come back
      # local_action:
        # module: wait_for
        # host: "{{ inventory_hostname }}"
        # delay: 10
        # timeout: 300
        # state: started
        # ignore_errors: yes

# run windows update all the boxes
# - include: win-updates.yml